name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            ls -a
            cd /home/www/projects/tatu_by_laser_remover/front
            git checkout .; git clean -fd; git pull; yarn build; killall node
          host: ${{ secrets.HOST }}
          username: www
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
