name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/projects/laser_remover_front
            git checkout .; git clean -fd; git pull; npm run build; killall node
            yarn
            yarn build
            npx pm2 restart ecosystem.config.js
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
