name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          user: www
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
            ls -al
            pwd
            cd /home/www/projects/tatu_by_laser_remover/front
            git checkout .; git clean -fd; git pull; yarn build; killall node
            
