name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: www
          key: ${{ secrets.SSH_PRIVATE_KEY }}
