name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: fifsky/ssh-action@master
        with:
          command: |
            source ~/.nvm/nvm.sh
            cd ~/projects/tatu_by_laser_remover/front
            git checkout .; git clean -fd; git pull; npm run build; killall node
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
