name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/www/projects/tatu_by_laser_remover/front
            git checkout .; git clean -fd; git pull; yarn build; killall node
          host: 45.8.251.158
          user: www
          key: ${{secrets.SSH_PRIVATE_KEY}}
          args: "-tt"
